---
language: java
install: true
script: $TARGET
jdk:
- openjdk7
- oraclejdk7
- oraclejdk8

env:
  matrix:
    - TARGET='mvn test'
    - TARGET='./gradlew test -s'

notifications:
  email:
    - michael@mosmann.de
    - m.joehren@gmail.com
